using EventBooking.API.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace EventBooking.API.Services
{
    public class PdfService
    {
        public byte[] GenerateBookingPdf(BookingDto booking)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    page.Header()
                        .Text("Event Booking Confirmation")
                        .FontSize(24)
                        .Bold();

                    page.Content()
                        .Column(col =>
                        {
                            col.Spacing(10);

                            col.Item().Text($"Booking ID: {booking.Id}");

                            col.Item().Text($"Event: {booking.EventTitle}");

                            col.Item().Text($"Tickets: {booking.TicketCount}");

                            col.Item().Text($"Amount Paid: ₹{booking.TotalAmount}");

                            col.Item().Text($"Status: {booking.Status}");

                            col.Item().Text($"Booked On: {booking.BookedAt:dd-MMM-yyyy hh:mm tt}");
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Event Booking System");
                });
            }).GeneratePdf();
        }
    }
}